In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from modelos import mv_to_ep

In [14]:
rukamay = 'S1A_OPER_SAR_EOSSP__CORE_L1A_OLF_20210726T185307_Spk_EC_BandMath.h5'
anguil = 'S1A_OPER_SAR_EOSSP__CORE_L1A_ARG-1_OLVF_20210618T143634_Spk_EC_BandMath.h5'
barrancosa = 'S1A_OPER_SAR_EOSSP__CORE_L1A_OLF_20210930T172207_Spk_EC_BandMath.h5'

path = 'Datos-humedad/2020-Enero-La Barrancosa-sensor_5.csv'
# path = 'Datos-humedad/2021-Enero-Anguil-sensor_5.csv'
# path = 'Datos-humedad/2021-Enero-Rukamay-sensor_150.csv'
# path = 'Datos-humedad/2021-Enero-Rukamay-sensor_70.csv'

data = pd.read_csv(path)
data

      Unnamed: 0                Fecha  cm   Humedad Profundidad
0              1  2019-07-22 11:30:15   5  0.077540    sensor_5
1              2  2019-07-22 12:30:15   5  0.075863    sensor_5
2              3  2019-07-22 13:30:15   5  0.075751    sensor_5
3              4  2019-07-22 14:30:15   5  0.075863    sensor_5
4              5  2019-07-22 15:30:15   5  0.078209    sensor_5
...          ...                  ...  ..       ...         ...
7495        7496  2020-02-04 21:30:15   5  0.208996    sensor_5
7496        7497  2020-02-04 22:00:15   5  0.205528    sensor_5
7497        7498  2020-02-04 22:30:15   5  0.204020    sensor_5
7498        7499  2020-02-04 23:00:15   5  0.200080    sensor_5
7499        7500  2020-02-04 23:30:15   5  0.201341    sensor_5

[7500 rows x 5 columns]

In [5]:
path = 'Datos-humedad/2021-Enero-Anguil-sensor_5.csv'
data = pd.read_csv(path)
data

       Unnamed: 0                Fecha  cm   Humedad Profundidad
0              25  2019-01-03 10:00:35   5  0.031035    sensor_5
1              26  2019-01-03 11:00:36   5  0.025983    sensor_5
2              27  2019-01-03 12:00:36   5  0.028971    sensor_5
3              28  2019-01-03 13:00:36   5  0.032088    sensor_5
4              29  2019-01-03 14:00:36   5  0.032964    sensor_5
...           ...                  ...  ..       ...         ...
14421       42279  2021-02-02 23:30:36   5  0.029929    sensor_5
14422       42280  2021-02-03 00:00:36   5  0.033813    sensor_5
14423       42281  2021-02-03 00:30:36   5  0.032189    sensor_5
14424       42282  2021-02-03 01:00:36   5  0.032189    sensor_5
14425       42283  2021-02-03 01:30:36   5  0.037018    sensor_5

[14426 rows x 5 columns]

In [6]:
path = 'Datos-humedad/2020-Enero-La Barrancosa-sensor_5.csv'
data = pd.read_csv(path)
data

      Unnamed: 0                Fecha  cm   Humedad Profundidad
0              1  2019-07-22 11:30:15   5  0.077540    sensor_5
1              2  2019-07-22 12:30:15   5  0.075863    sensor_5
2              3  2019-07-22 13:30:15   5  0.075751    sensor_5
3              4  2019-07-22 14:30:15   5  0.075863    sensor_5
4              5  2019-07-22 15:30:15   5  0.078209    sensor_5
...          ...                  ...  ..       ...         ...
7495        7496  2020-02-04 21:30:15   5  0.208996    sensor_5
7496        7497  2020-02-04 22:00:15   5  0.205528    sensor_5
7497        7498  2020-02-04 22:30:15   5  0.204020    sensor_5
7498        7499  2020-02-04 23:00:15   5  0.200080    sensor_5
7499        7500  2020-02-04 23:30:15   5  0.201341    sensor_5

[7500 rows x 5 columns]

In [46]:
data.columns

Index(['Unnamed: 0', 'Fecha', 'cm', 'Humedad', 'Profundidad'], dtype='object')

In [15]:
hum = data.Fecha.tolist()

inp = barrancosa

# date = inp[33:37]+'-'+inp[37:39]+'-'+inp[39:41]


out = []
indice = []
#aaaa-mm-dd
# date = '2021-02-01'
# date = '2019-10-19' #rukamay1
# date = '2020-09-19' #rukamay6 No hay datos
date = '2020-01-01' #barrancosa2
# date = '2019-10-13' #barramcosa1

i = 0
while (hum[i][0:10] != date and i+1 < len(hum)): 

    if hum[i+1][0:10] == date:
        j = i
        while hum[j+1][0:10] == date:
            
            out.append(hum[j+1])
            indice.append(j+1)
            j = j+1

    i = i+1    
    

    
# print(indice)
# for i in indice: 
#     print(hum[i])

print(out) #mediciones por hora de la fecha 'date' 
humedad = np.asarray(data.Humedad.tolist())
humedadDia = humedad[indice] #humedad medida en cada hora

['2020-01-01 00:00:15', '2020-01-01 00:30:15', '2020-01-01 01:00:15', '2020-01-01 01:30:15', '2020-01-01 02:00:15', '2020-01-01 02:30:15', '2020-01-01 03:00:15', '2020-01-01 03:30:15', '2020-01-01 04:00:15', '2020-01-01 04:30:15', '2020-01-01 05:00:15', '2020-01-01 05:30:15', '2020-01-01 06:00:15', '2020-01-01 06:30:15', '2020-01-01 07:00:15', '2020-01-01 07:30:15', '2020-01-01 08:00:15', '2020-01-01 10:00:15', '2020-01-01 11:00:15', '2020-01-01 12:00:15', '2020-01-01 13:00:15', '2020-01-01 14:00:15', '2020-01-01 15:00:15', '2020-01-01 16:00:15', '2020-01-01 17:00:15', '2020-01-01 18:00:15', '2020-01-01 18:30:15', '2020-01-01 19:00:15', '2020-01-01 19:30:15', '2020-01-01 20:00:15', '2020-01-01 20:30:15', '2020-01-01 21:30:15', '2020-01-01 22:00:15', '2020-01-01 22:30:15', '2020-01-01 23:00:15', '2020-01-01 23:30:15']

In [17]:
# hora = '10:53' #rukamay1
hora = '09:33' #barrancosa1
hora = '10:00'

indhora = []
for i in range(len(out)):
    if out[i][11:13] == hora[0:2]:
        print(out[i])
        indhora = i
        
# indhora = np.asarray(indhora)
# print(indhora)
print(out[indhora-1:indhora+3])        
humedadOut = humedadDia[indhora-1:indhora+3]

2020-01-01 10:00:15
['2020-01-01 08:00:15', '2020-01-01 10:00:15', '2020-01-01 11:00:15', '2020-01-01 12:00:15']

In [23]:
humedadmedia = np.zeros(len(humedadOut))
for i in range(len(humedadOut)):
    humedadmedia[i] = np.real(mv_to_ep(humedadOut[i],0.6,0.4,0)['ep']) #Tomo solo parte real

error = np.std(humedadmedia)/np.sqrt(len(humedadmedia))

print(humedadmedia)
print(np.mean(humedadmedia), 'pm', error)
out = np.mean(humedadmedia)
# [out,error]

[5.32740152 5.27485802 5.32005327 5.32208762]
5.311100105007032 pm 0.010547836377030752

In [24]:

# np.savetxt('Inferencia/InputsInferencia/humedadmediaRukamay1.txt',[out, error])
# np.savetxt('Inferencia/InputsInferencia/humedadmediaBarrancosa1.txt',[out, error])
np.savetxt('Inferencia/InputsInferencia/humedadmediaBarrancosa2.txt',[out, error])